In [1]:
from google.colab import files
uploaded = files.upload()

Saving retail_sales_sample.csv to retail_sales_sample.csv

In [2]:
import pandas as pd

df = pd.read_csv("retail_sales_sample.csv")
df.head()

,Order ID,Order Date,Customer ID,Product ID,Category,Region,Sales,Profit
0,ORD1000,2023-12-26,CUST25,PROD14,Office Supplies,South,4422.98,-836.25
1,ORD1001,2023-01-17,CUST44,PROD5,Furniture,Central,470.38,81.93
2,ORD1002,2023-05-12,CUST23,PROD6,Technology,South,4186.33,1012.24
3,ORD1003,2023-06-10,CUST29,PROD19,Technology,South,962.53,275.54
4,ORD1004,2023-10-09,CUST2,PROD9,Office Supplies,West,1917.44,443.85

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     200 non-null    object
 1   Order Date   200 non-null    object
 2   Customer ID  200 non-null    object
 3   Product ID   200 non-null    object
 4   Category     200 non-null    object
 5   Region       200 non-null    object
 6   Sales        200 non-null    float64
 7   Profit       200 non-null    float64
dtypes: float64(2), object(6)
memory usage: 12.6+ KB

In [4]:
df.isnull().sum()

Order ID       0
Order Date     0
Customer ID    0
Product ID     0
Category       0
Region         0
Sales          0
Profit         0
dtype: int64

In [8]:
df = df.drop_duplicates()
print("Duplicates removed ✅")

Duplicates removed ✅

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_id', 'category',
       'region', 'sales', 'profit'],
      dtype='object')

In [12]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['sales'] = df['sales'].astype(float)
df['profit'] = df['profit'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     200 non-null    object
 1   order_date   200 non-null    datetime64[ns]
 2   customer_id  200 non-null    object
 3   product_id   200 non-null    object
 4   category     200 non-null    object
 5   region       200 non-null    object
 6   sales        200 non-null    float64
 7   profit       200 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 12.6+ KB

In [13]:
df['profit_margin'] = df['profit'] / df['sales']
df.head()

,order_id,order_date,customer_id,product_id,category,region,sales,profit,profit_margin
0,ORD1000,2023-12-26,CUST25,PROD14,Office Supplies,South,4422.98,-836.25,-0.189069
1,ORD1001,2023-01-17,CUST44,PROD5,Furniture,Central,470.38,81.93,0.174178
2,ORD1002,2023-05-12,CUST23,PROD6,Technology,South,4186.33,1012.24,0.241797
3,ORD1003,2023-06-10,CUST29,PROD19,Technology,South,962.53,275.54,0.286266
4,ORD1004,2023-10-09,CUST2,PROD9,Office Supplies,West,1917.44,443.85,0.231481

In [14]:
customers = df[['customer_id', 'region']].drop_duplicates()
customers.head()

  customer_id   region
0      CUST25    South
1      CUST44  Central
2      CUST23    South
3      CUST29    South
4       CUST2     West

In [15]:
orders = df[['order_id', 'order_date', 'customer_id', 'sales', 'profit', 'profit_margin']]
orders.head()

  order_id order_date customer_id    sales   profit  profit_margin
0  ORD1000 2023-12-26      CUST25  4422.98  -836.25      -0.189069
1  ORD1001 2023-01-17      CUST44   470.38    81.93       0.174178
2  ORD1002 2023-05-12      CUST23  4186.33  1012.24       0.241797
3  ORD1003 2023-06-10      CUST29   962.53   275.54       0.286266
4  ORD1004 2023-10-09       CUST2  1917.44   443.85       0.231481

In [16]:
products = df[['product_id', 'category']].drop_duplicates()
products.head()

  product_id         category
0     PROD14  Office Supplies
1      PROD5        Furniture
2      PROD6       Technology
3     PROD19       Technology
4      PROD9  Office Supplies

In [17]:
customers.to_csv("customers.csv", index=False)
orders.to_csv("orders.csv", index=False)
products.to_csv("products.csv", index=False)

print("Files saved successfully ✅")

Files saved successfully ✅

In [18]:
print("Original rows:", len(df))
print("Customers rows:", len(customers))
print("Orders rows:", len(orders))
print("Products rows:", len(products))

Original rows: 200
Customers rows: 132
Orders rows: 200
Products rows: 78